/**
 * Collects every cashier string in the register app — each t('…') and tk('…') literal, plus the
 * permission labels the override prompt shows — and writes them to packages/shared/src/i18n-cashier.ts
 * (P18b, ADR 0028). Run after changing register text:
 *
 *   pnpm --filter @adpay/register i18n:extract
 *
 * A register test fails when the committed list and the source disagree.
 */
import { PERMISSIONS } from '@adpay/shared';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = join(dirname(fileURLToPath(import.meta.url)), '..');
export const TARGET = join(APP, '../../packages/shared/src/i18n-cashier.ts');

function files(dir: string): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? files(p) : /\.tsx?$/.test(f) ? [p] : [];
  });
}

/** Every key in source order of first appearance, deduplicated. */
export function collectKeys(): string[] {
  const keys = new Set<string>();
  const call = /\bt(?:k)?\(\s*'((?:[^'\\]|\\.)*)'/g;
  // The customer screen speaks the customer's language through the customer catalog (ADR 0027).
  const cashierFiles = [...files(join(APP, 'src')), join(APP, 'App.tsx')].filter((f) => !f.endsWith('CustomerScreen.tsx'));
  for (const f of cashierFiles) {
    const src = readFileSync(f, 'utf8');
    for (const m of src.matchAll(call)) keys.add(m[1]!.replace(/\\(.)/g, '$1'));
  }
  for (const p of Object.values(PERMISSIONS)) keys.add(p.label);
  return [...keys].sort((a, b) => a.localeCompare(b, 'en'));
}

export function render(keys: string[]): string {
  const q = (k: string) => `'${k.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  return `/**
 * The register's cashier-side strings (P18b, ADR 0028), keyed by their English text.
 *
 * GENERATED by \`pnpm --filter @adpay/register i18n:extract\` from every t('…') and tk('…') in the
 * register app, plus the permission labels. Don't edit by hand: use t('…') in the register and run
 * the script. Spanish is in i18n-cashier-es.ts; every other language is filled in admin → Translations.
 */
export const CASHIER_EN = [
${keys.map((k) => `  ${q(k)},`).join('\n')}
] as const;

export type CashierKey = (typeof CASHIER_EN)[number];
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const keys = collectKeys();
  writeFileSync(TARGET, render(keys));
  console.log(`${keys.length} cashier strings → ${TARGET}`);
}
